# Generated by Django 4.2.5 on 2023-09-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finecap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservas',
            old_name='cnpj',
            new_name='CNPJ',
        ),
        migrations.AlterField(
            model_name='reservas',
            name='categoria_empresa',
            field=models.CharField(max_length=100),
        ),
    ]
