# Generated by Django 4.2.5 on 2023-09-20 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finecap', '0002_rename_cnpj_reservas_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
